# Generated by Django 2.0 on 2018-01-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttraction',
            fields=[
                ('uaId', models.AutoField(primary_key=True, serialize=False)),
                ('provinceId', models.IntegerField()),
                ('clusterId', models.IntegerField()),
                ('photoCount', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
            options={
                'db_table': 'user_attraction',
            },
        ),
    ]
