# Generated by Django 2.0 on 2018-01-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attraction', '0003_auto_20180125_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAttraction',
            fields=[
                ('paId', models.AutoField(primary_key=True, serialize=False)),
                ('photoId', models.IntegerField()),
                ('provinceId', models.CharField(max_length=255)),
                ('clusterId', models.IntegerField()),
            ],
            options={
                'db_table': 'photo_attraction',
            },
        ),
        migrations.RemoveField(
            model_name='userattraction',
            name='clusterId',
        ),
        migrations.RemoveField(
            model_name='userattraction',
            name='provinceId',
        ),
        migrations.AddField(
            model_name='userattraction',
            name='attractionId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userattraction',
            name='userName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userattraction',
            name='photoCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userattraction',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
