# Generated by Django 2.0 on 2018-01-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attraction', '0004_auto_20180125_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoattraction',
            name='provinceId',
            field=models.IntegerField(),
        ),
    ]
