# Generated by Django 2.0 on 2018-01-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attraction', '0005_auto_20180125_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattraction',
            name='attractionId',
        ),
        migrations.AddField(
            model_name='userattraction',
            name='clusterId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userattraction',
            name='provinceId',
            field=models.IntegerField(default=0),
        ),
    ]
