# Generated by Django 2.0 on 2018-01-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attraction', '0006_auto_20180125_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionSimilarityMatrix',
            fields=[
                ('asmId', models.AutoField(primary_key=True, serialize=False)),
                ('province1Id', models.IntegerField()),
                ('clusterI1d', models.IntegerField()),
                ('province2Id', models.IntegerField()),
                ('cluster2Id', models.IntegerField()),
                ('similarity', models.FloatField()),
            ],
            options={
                'db_table': 'attraction_similarity_matrix',
            },
        ),
    ]
