# Generated by Django 2.0 on 2018-01-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attraction', '0007_attractionsimilaritymatrix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractionsimilaritymatrix',
            old_name='clusterI1d',
            new_name='cluster1Id',
        ),
    ]
