# Generated by Django 2.0 on 2018-01-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='User',
        ),
    ]
