# Generated by Django 2.0 on 2018-01-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0002_auto_20180124_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
