# Generated by Django 2.0 on 2018-01-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0003_auto_20180124_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoFlikerId',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
