# Generated by Django 2.0 on 2018-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0006_auto_20180124_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
