# Generated by Django 2.0 on 2018-01-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0008_auto_20180124_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='downloadURL',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='filePath',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='isVideo',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pageURL',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoFlikerId',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='province',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='takenDate',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.TextField(default='', null=True),
        ),
    ]
