# Generated by Django 2.0 on 2018-01-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0009_auto_20180124_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='downloadURL',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='filePath',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pageURL',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoFlikerId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='province',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='takenDate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
