# Generated by Django 2.0 on 2018-01-25 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0010_auto_20180125_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='province',
            new_name='provinceId',
        ),
    ]
