# Generated by Django 2.0 on 2018-01-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0011_auto_20180125_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('provinceId', models.AutoField(primary_key=True, serialize=False)),
                ('provinceName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'province',
            },
        ),
    ]
