# Generated by Django 2.0 on 2018-01-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0012_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='nameInFile',
            field=models.CharField(default='', max_length=255),
        ),
    ]
