# Generated by Django 2.0 on 2018-02-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0017_auto_20180125_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
