# Generated by Django 2.0 on 2018-02-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0018_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photoFlikerId',
        ),
    ]
