# Generated by Django 2.0 on 2018-02-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0019_auto_20180217_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
